<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>

            //Synchromous=>  One statement runs after the other line by line sequentially in a single thread.
            //Asynchoronous=>Allows async func to run in background so that no-blocking takes place and 
                                    //all the functions run parallely


            //Event Loop=>

                    //Web Api's live outside the JS Engine .Stuff like DOM Manipulation, SetTimeout ,Http Request,Ajax Calls live outside JS engine and we can access to them as they are part of JS runtime

                    //The call back func which is present in the Web API's moves to the Message Queue , once the timer set in the SetTimeout func gets finished.This callback func waits in the Message Queue to be executed in the Execution Stack once the Execution Stack is empty 

                    //Event Loop constantly monitors the execution stack and it pushes the first callback func into the Exceution Stack as soon as the execution stack is empty .Once this callback is pushed onto the Execution Stack , a new Execution Context is created.                 

        //        const second1 = () => {
        //     setTimeout(() => {
        //         console.log('Async Hey there');
        //     }, 2000);
        // }

        // const second2 = () => {
        //     setTimeout(() => {
        //         console.log('Async Hey there');
        //     }, 2000);
        // }

        // const first = () => {
        //     console.log('Hey there');
        //     second2();
                //if second1 is used it is sync however if second2 is used , it is async 
        //     console.log('The end');
        // }

        // first();

            //Call Back Hell (Callback inside callback inside callback)

        // function getRecipe() {
        //     setTimeout(() => {
        //         const recipeID = [523, 883, 432, 974];
        //         console.log(recipeID);

                    //The Third argument to the callback func is actually the id value
        //         setTimeout(id => {
        //             const recipe = {title: 'Fresh tomato pasta', publisher: 'Jonas'};
        //             console.log(`${id}: ${recipe.title}`);

        //             setTimeout(publisher => {
        //                 const recipe2 = {title: 'Italian Pizza', publisher: 'Jonas'};
        //                 console.log(recipe);
        //             }, 1500, recipe.publisher);

        //         }, 1500, recipeID[2]);

        //     }, 1500);
        // }
        // getRecipe();



        //Promises
        //=>Object that keeps track about whether a certain event has happened already or not .
        //=>It also determines what happens next.
        //=>Implements the concept of future value that we're expecting.


        // const getIDs = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve([523, 883, 432, 974]);
        //     }, 1500);
        // });

            //then is inherited by Promise and is called when the Promise is successful(takes care whatever is present with resolve)
            //catch is also inherited by Promise and is called when Promise has failed(takes care whatever is present with reject)

        // const getRecipe = recID => {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(ID => {
        //             const recipe = {title: 'Fresh tomato pasta', publisher: 'Jonas'};
        //             resolve(`${ID}: ${recipe.title}`);
        //         }, 1500, recID);
        //     });
        // };

        // const getRelated = publisher => {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(pub => {
        //             const recipe = {title: 'Italian Pizza', publisher: 'Jonas'};
        //             resolve(`${pub}: ${recipe.title}`);
        //         }, 1500, publisher);
        //     });
        // };

        // getIDs
        // .then(IDs => {
        //     console.log(IDs);
        //     return getRecipe(IDs[2]);//This returns a promise
        // })
        // .then(recipe => {
        //     console.log(recipe);
        //     return getRelated('Jonas Schmedtmann');
        // })
        // .then(recipe => {
        //     console.log(recipe);
        // })
        // .catch(error => {
        //     console.log('Error!!');
        // });

            //async-await(designed to consume promises)

        // async function getRecipesAW() {
            //await can only be used inside a async func
        //     const IDs = await getIDs;//await will stop the code from executing till promise is fullfilled(await for      the promise to get resolved )
        //     console.log(IDs);
        //     const recipe = await getRecipe(IDs[2]);
        //     console.log(recipe);
        //     const related = await getRelated('Jonas Schmedtmann');
        //     console.log(related);

        //     return recipe;
        // }
        // getRecipesAW().then(result => console.log(`${result} is the best ever!`));

         //AJAX =>Asynchronous Javascript And Xml(Allows us to asynchronously communicate with remote servers)
         //AJAX calls helps to get data from server and post data to server using an API    
        function getWeather(woeid) {
            //fetch api gets data and returns a promise 
            fetch(`https://crossorigin.me/https://www.metaweather.com/api/location/${woeid}/`)
            .then(result => {
                // console.log(result);
                return result.json();
            })
            .then(data => {
                // console.log(data);
                const today = data.consolidated_weather[0];
                console.log(`Temperatures today in ${data.title} stay between ${today.min_temp} and ${today.max_temp}.`);
            })
            .catch(error => console.log(error));
        }
        getWeather(2487956);
        getWeather(44418);

            //using async with api's
        async function getWeatherAW(woeid) {
            try {
                const result = await fetch(`https://crossorigin.me/https://www.metaweather.com/api/location/${woeid}/`);
                const data = await result.json();
                const tomorrow = data.consolidated_weather[1];
                console.log(`Temperatures tomorrow in ${data.title} stay between ${tomorrow.min_temp} and ${tomorrow.max_temp}.`);
                return data;
            } catch(error) {
                alert(error);
            }
        }
        getWeatherAW(2487956);
        

        const mydata=getWeatherAW(44418);
        console.log(mydata);//This does not work , because console.log works synchronousy and is called before mydata is  received .So we actually running this line when we dont have the data with us

        //if we want this to work, we need .then func which console logs the data returned from the  promise
        let dataLondon;
        getWeatherAW(44418).then(data => {
            dataLondon = data
            console.log(dataLondon);
        });

    </script>
</body>
</html>